resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml
- name: Codeql.Enabled
  value: false
- name: PIP_INDEX_URL

jobs:
- job: AddWindowsDependencies
  displayName: Add Windows Dependencies
  pool:
    name: ${{ variables.windows_pool }}
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: 3.11
  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: 'public/azure-cli-feed'
  - template: .azure-pipelines/templates/azdev_setup.yml

- job: AddUbuntuDependencies
  displayName: Add Ubuntu Dependencies
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: 3.11
  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: 'public/azure-cli-feed'
  - template: .azure-pipelines/templates/azdev_setup.yml

- job: AddMacosDependencies
  displayName: Add macOS Dependencies
  pool:
    vmImage: ${{ variables.macos_pool }}
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: 3.11
  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: 'public/azure-cli-feed'
  - template: .azure-pipelines/templates/azdev_setup.yml

